### PR TITLE
Add tooltip for run button explaining else

### PR DESCRIPTION
**Pull request by Destroy666x**
Very simple change that unhides a feature of running else part of macros, which I spotted randomly when looking for something entirely else :P

Not sure if it's the best way to phrase the message, but feel free to correct.

### CODE REVIEW

**Comment by Destroy666x** [comment]
BTW, I think Shift is better modifier for such state changes. As, as the name suggests, it shifts something and is normally used as the primary key for that purpose.

I didn't change it since it may be inconsistent with something or chosen for some reason I don't know. Let me know why it's Ctrl @WarmUpTill and if changing it makes sense

**Comment by WarmUpTill** [comment]
I did not choose SHIFT as I did not want the button to flicker while typing capitalized letters.
But I won't oppose a change to SHIFT if you think it makes the most sense.

I guess ALT could also be considered since it alters the behaviour of the button. :)

**Comment by Destroy666x** [comment]
> To be honest I forgot that I even added that feature! :D

Oh :P 

> I did not choose SHIFT as I did not want the button to flicker while typing capitalized letters.

Makes sense, I thought the inputs would intercept the keys. I'll switch to Alt

**Comment by Destroy666x** [comment]
I went for a different solution - the button changes state only when mouse is over it. It required some workarounds, but don't think there's a better way of doing it with Qt.

I guess this can be merged if it's fine

**Pull request merged**
