### PR TITLE
Specify scenes to exclude from Region triggers

### PR DESCRIPTION
**Pull request by kieve**
Adds an option to exclude a region triggered scene switch if you're currently in the specified Scene.

Demo of why (and how it works):
https://www.youtube.com/watch?v=NpbLOD6wE5w

Note:
~~When I installed the OBS dev environment and started using Region switches, sometimes they stopped triggering properly.
I don't think this is a result of my changes. I do believe this is a bug in master, but I haven't confirmed yet.~~
I'm an idiot. Imagine forgetting you have a pause setting that you forgot to delete.
All good. These changes work as I intended and expect.

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Thanks for the PR! 
I will check it out later today.

Just for my understanding:
Your main problem was that you want to have a different transition depending on whether you previously were on your right or left monitor, correct?

If so, could this not have been done with the transitions tab?
So something like this:
```
Switch from "left scene" -> "middle scene" using "left slide"
Switch from "right scene" -> "middle scene" using "right slide"
```

**Comment by WarmUpTill** [comment]
You seem to have accidentally removed the `slot `macro from the scene group functions of the generic switch widget here:
https://github.com/kieve/SceneSwitcher/blob/c1997cb833a4c90e73fb0793e7f3f73acaf32521/src/headers/switch-generic.hpp#L77-L81
This will cause all of these scene group related signals to be missed by any widget that is inheriting from the generic switch widget.

You probably meant to do something like this:
```
class SwitchWidget : public QWidget {
	Q_OBJECT

public:
	SwitchWidget(QWidget *parent, SceneSwitcherEntry *s,
		     bool usePreviousScene = true, bool addSceneGroup = false);
	virtual SceneSwitcherEntry *getSwitchData();
	virtual void setSwitchData(SceneSwitcherEntry *s);

	static void swapSwitchData(SwitchWidget *s1, SwitchWidget *s2);

protected slots:
	void SceneChanged(const QString &text);
	void TransitionChanged(const QString &text);
	virtual void SceneGroupAdd(const QString &name);
	virtual void SceneGroupRemove(const QString &name);
	virtual void SceneGroupRename(const QString &oldName,
				      const QString &newName);

protected:
	bool loading = true;

	QComboBox *scenes;
	QComboBox *transitions;

	SceneSwitcherEntry *switchData;
```

In general what is the purpose of the reimplementation of `SceneGroupAdd`, `SceneGroupRemove `and `SceneGroupRename `in `ScreenRegionWidget`?
`excludeScenes `does not seem to be using any SceneGroups.

(I apologize in advance if  I am missing something obvious)

**Comment by kieve** [comment]
Naw, that's all a huge misunderstanding of my understanding in how Scene Groups work.
I'll go over it again and try to minimize the changes.

Thanks for looking over it!

**Comment by kieve** [comment]
> Thanks for the PR!
> I will check it out later today.
> 
> Just for my understanding:
> Your main problem was that you want to have a different transition depending on whether you previously were on your right or left monitor, correct?
> 
> If so, could this not have been done with the transitions tab?
> So something like this:
> 
> ```
> Switch from "left scene" -> "middle scene" using "left slide"
> Switch from "right scene" -> "middle scene" using "right slide"
> ```

So, the main reason is that I want my Camera to remain static, using slide transitions also slides my camera resulting in the camera sliding off, then back on to the screen.

To avoid this, I implemented the slide animation into the scene switches using the [Motion Effect](https://obsproject.com/forum/resources/motion-effect.668/), which lets me add a source animation on scene switch, per scene.

But, that resulted in needing two different scenes and trigger in AdvancedSceneSwitcher, as I demo'd.

I'll admit, I haven't spent much time on alternatives. AdvancedSceneSwitcher so far is the only plugin I've found that lets me follow the mouse without having to use hotkeys, but seems restricted to specifically scene switches and transitions.

**Comment by WarmUpTill** [comment]
>To avoid this, I implemented the slide animation into the scene switches using the Motion Effect, which lets me add a source animation on scene switch, per scene.
But, all transitions are "Cut", meaning the Camera stays in place (since it's positioned in each scene, in the same place).

Ah thanks for the explanation!
I just assumed that you were talking about and using slide transitions when watching the video.

**Comment by WarmUpTill** [comment]
Thanks for the update!

If you don't have any further changes planned I will merge the PR the next time I get around to spending some more time on this plugin.
I will probably perform some minor changes afterwards, but leave the functionality as is.

**Comment by kieve** [comment]
Sounds good!
No rush, I'm perfectly content running OBS from source, since it's so easy to port over plugins and it shares settings globally.

**Pull request merged**
