### PR TITLE
Create fr-FR.ini

### PR DESCRIPTION
**Pull request by lMagickl**
add french language

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Thank you so much!

**Comment by WarmUpTill** [comment]
I fixed the few minor issues with https://github.com/WarmUpTill/SceneSwitcher/pull/863/commits/2210d40de6a59cac18e3b7502f886a90c32a181b.
Let me know if that seems fine to you and I will merge the changes! :)

**Comment by lMagickl** [comment]
WARNING: Locale entry "AdvSceneSwitcher.action.switchScene" from "data/locale/fr-FR.ini" not found in "en-US.ini"
its seems that you need to fix the en-US.ini because when I set it to AdvSceneSwitcher.action.scene and not to AdvSceneSwitcher.actions.switchScene The trad is not translated: 
image
and 
AdvSceneSwitcher.action.switchScene="Changer de scène" occurs this : 
image
which works.
Also, It seems that this line occurs a bug : AdvSceneSwitcher.action.scene.entry="Changer la scène{{sceneTypes}}{{scenes}}en utilisant{{transitions}}avec une durée de{{duration}}secondes"
image

**Comment by WarmUpTill** [comment]
>WARNING: Locale entry "AdvSceneSwitcher.action.switchScene" from "data/locale/fr-FR.ini" not found in "en-US.ini"
its seems that you need to fix the en-US.ini because when I set it to AdvSceneSwitcher.action.scene and not to AdvSceneSwitcher.actions.switchScene The trad is not translated

This was changed recently, to make it more consistent with the other macro locale entries.
I assume you are not using a build from the master branch, but one of the latest releases, where this change was not yet included. :)

This is what it looks like when using the [build](https://github.com/WarmUpTill/SceneSwitcher/actions/runs/6129807815?pr=863) created with your PR:

image

Does that look / sound correct?

**Comment by lMagickl** [comment]
Indeed, I dont use the last build so yeah its fine i think you can merge the changes

**Pull request merged**
