### PR TITLE
Create CI test for Debian packaging (in Ubuntu 20.04)

### PR DESCRIPTION
**Pull request by eribertomota**
This PR will help to test the alone build of the SceneSwitcher.

This is a very basic packaging to test SceneSwitcher. The final package in Debian will be a bit different and improved.

To make changes, edit the build-debian.yml and debian/rules. In build-debian.yml is possible add new build dependencies. In debian/rules is possible change the build variables. Note that Debian build system (debhelper) already add some variables automatically. Please, check the build log provided by CI test.

Please, feel free to ask me for future changes, improvements and fixes.

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Thank you very much!
I just performed some minor changes:
* rebase to master to the cmake changes are included
* move CI files from .github/ to the CI/ folder
* adjust dependencies to include libxss-dev
* checkout submodules

Unforunately it looks like the `obs-frontend-api.h` header seems to be missing in the `libobs-dev` package now:
```
ls -l /usr/include/obs/
drwxr-xr-x 3 root root  4096 Sep 12 10:42 audio-monitoring
drwxr-xr-x 2 root root  4096 Sep 12 10:42 callback
drwxr-xr-x 3 root root  4096 Sep 12 10:42 graphics
drwxr-xr-x 2 root root  4096 Sep 12 10:42 media-io
-rw-r--r-- 1 root root  9014 Mar 24  2020 obs-audio-controls.h
-rw-r--r-- 1 root root  2099 Mar 24  2020 obs-avc.h
-rw-r--r-- 1 root root  2139 Mar 24  2020 obs-config.h
-rw-r--r-- 1 root root 16105 Mar 24  2020 obs-data.h
-rw-r--r-- 1 root root  1794 Mar 24  2020 obs-defs.h
-rw-r--r-- 1 root root  8551 Mar 24  2020 obs-encoder.h
-rw-r--r-- 1 root root  1185 Mar 24  2020 obs-ffmpeg-compat.h
-rw-r--r-- 1 root root 10731 Mar 24  2020 obs-hotkey.h
-rw-r--r-- 1 root root 18208 Mar 24  2020 obs-hotkeys.h
-rw-r--r-- 1 root root  1585 Mar 24  2020 obs-interaction.h
-rw-r--r-- 1 root root 30616 Mar 24  2020 obs-internal.h
-rw-r--r-- 1 root root  7025 Mar 24  2020 obs-module.h
-rw-r--r-- 1 root root  2603 Mar 24  2020 obs-output.h
-rw-r--r-- 1 root root 14764 Mar 24  2020 obs-properties.h
-rw-r--r-- 1 root root  2430 Mar 24  2020 obs-scene.h
-rw-r--r-- 1 root root  2610 Mar 24  2020 obs-service.h
-rw-r--r-- 1 root root 16695 Mar 24  2020 obs-source.h
-rw-r--r-- 1 root root  6104 Mar 24  2020 obs-ui.h
-rw-r--r-- 1 root root 79939 Mar 24  2020 obs.h
-rw-r--r-- 1 root root  7675 Mar 24  2020 obs.hpp
-rw-r--r-- 1 root root  1365 Mar 28  2020 obsconfig.h
drwxr-xr-x 3 root root  4096 Sep 12 10:42 util
```
Not sure why that is, but without it the plugin cannot be built.

**Comment by eribertomota** [comment]
Em domingo, 12 de setembro de 2021,
>
>
>
> Unforunately it looks like the obs-frontend-api.h header seems to be
> missing in the libobs-dev package now:
>
>
>
> In OBS 25 the Debian package wasn't install this header. I will try fix it
today. Thanks!

**Comment by WarmUpTill** [comment]
>In OBS 25 the Debian package wasn't install this header. I will try fix it today. Thanks!

Ah I see - no rush, take your time! :)
Thank you!

**Comment by eribertomota** [comment]
Em domingo, 12 de setembro de 2021, WarmUpTill ***@***.***>
escreveu:

> In OBS 25 the Debian package wasn't install this header. I will try fix it
> today. Thanks!
>
> Ah I see - no rush, take your time! :)
>
I will be able to make it soon. In some hours.

**Comment by eribertomota** [comment]
I fixed the test. You code need a little fix to build in Debian. Congratulations!!!

**Comment by WarmUpTill** [comment]
I added more backwards comparability checks to support OBS 25 and your new test seems to work as expected.
Thank you very much for your support!

**Comment by eribertomota** [comment]
Built on Debian! \o/

Today I will start the packaging to send to Debian. I will open a new issue to allow us follow the process.

**Comment by eribertomota** [comment]
> I added more backwards comparability checks to support OBS 25 and your new test seems to work as expected.
> Thank you very much for your support!

It is very good for me because I will package over libobs from OBS 27 in Debian Sid, but I will also put it in Debian  Stable Backports (OBS 26).

**Pull request merged**
