### PR TITLE
Out of tree builds

### PR DESCRIPTION
**Pull request by c3r1c3**
This PR enables out-of-tree builds, saving time and trouble for developers and testers.

Please test, especially on Mac because I don't have access to my Mac at this time.

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Thank you very much for this! I am very interested into merging this!

Here is the result of my testing: 

I managed to build the scene swichter on Windows and Ubuntu using the new cmake, but I had to modify it slightly. (I had to remove the obs-frontend-api from the target_link_libraries calls)
I am by no means a CMake expert so I maybe this was only needed, because I messed something up in my build environment.

I did not yet manage to build it on Mac using the new CMake:
I had the issue that the CMAKE_AUTOMOC/CMAKE_AUTOUIC for some reason was looking for the *ui file in the wrong directory - src/headers/advanced-scene-switcher.ui .
After resolving this issue by manually creating the needed header files, the build failed as the include for QmainWindow was not found. Is it necessary to set additional CMake Variables, not mentioned in the README?
Unfortunately I will most likely not have the time to look into Mac issues next week, but I will try my best.

Were you able to successfully build the scene switcher on Windows / Linux / Mac? If you did, I will merge the pull request and just assume that I ran into issues due to misconfiguration on my end.

**Comment by c3r1c3** [comment]
I was able to build on Linux with no issues.

I was able to run cmake without issues on Windows. I have VS2017 and I get a compile error using the defaults in VS2017. That error is because one is no longer allowed to reassign a (Q)String to a WChar or Char (which happens twice in the code, both in advanced-scene-switcher-win.cpp, lines 124 and 145, VS2017 Error Code #C2664).  I do want to address that, but figured that since the error is coming from VS2017 (and not any changes I made to the code) that should be treated in a separate patch.

As to MacOS/OS X, my computer only goes to 10.12, but since it's back up and running I can at least try to test it now and fix any issues.

I would hold-off on applying the PR at least until I can check on OS X (and fix any issues on there).

**Comment by c3r1c3** [comment]
Quick update: I fixed a few issues with the CMakeLists.txt file. Still testing and working on the Mac version. As soon as I finish that I will push up those fixes and then take a look at the Linux stuff to make sure it's building correctly. If that passes, then I think we'll be good for inclusion.

**Comment by WarmUpTill** [comment]
Thanks for the update!

**Comment by c3r1c3** [comment]
Working so far on OS X. About to re-test on Linux and Windows.

Includes several fixes, but the build instructions need to be updated.

**Comment by c3r1c3** [comment]
Okay, should be building everywhere. I need to finish the new build instructions. Will do that 'tomorrow'.

**Comment by WarmUpTill** [comment]
Thank you very much for your awesome work! 
Looking forward to the update 'tomorrow' :)

I will test it once more on my end in the mean time.

**Comment by c3r1c3** [comment]
There we go. Please let me know what you find.

**Comment by WarmUpTill** [comment]
Looks good to me.
I was able to successfully build on Windows and Mac. (Will test Linux tomorrow)
If you do not have any further changes planned i will merge it tomorrow.

**Comment by c3r1c3** [comment]
No further changes planned.

**Pull request merged**
