### PR TITLE
Add portuguese brazil translation

### PR DESCRIPTION
**Pull request by junior-anzolin**
Create file pr-BR with translation to Portuguese BR

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Thank you very much!
I really appreciate your work!

Just a few minor issues popped up:
```
ERROR: Locale entry "AdvSceneSwitcher.action.wait.entry.fixed" from "data/locale/pt-BR.ini:736" does not contain "{{waitType}}" widget placeholder
ERROR: Locale entry "AdvSceneSwitcher.action.wait.entry.random" from "data/locale/pt-BR.ini:737" does not contain "{{waitType}}" widget placeholder
```

Once those are resolved I will merge the PR.
Or if you want I can fix it myself. :)

**Comment by junior-anzolin** [comment]
Thank you for your time, I fix the problem here, can you check?

I'm not shure if the file name is correct, can you check this please?

Another question, how can I put this file in plugin installed in my MacOS?

**Comment by junior-anzolin** [comment]
I found where my file should go and it works! I'm very happy =D

image

**Comment by WarmUpTill** [comment]
Looks good! :)
Thank you again!

**Pull request merged**
