### PR TITLE
Add more basic Twitch conditions, simplify some code and make it more consistent

### PR DESCRIPTION
**Pull request by Destroy666x**
This PR:
- adds all basic Twitch EventSub conditions, except ones marked as beta, incompatible with websockets and one not too useful user one
- allows multiple token permissions per condition
- refactors code:
1. Simplifies generic Twitch event related functions for much less code. More advanced logic can go into new functions.
2. Separates basic events (which are always nice to have unchanged to just bump versions and quickly test in case of changes), advanced logic events and polling in a clearer and more consistent way.
3. Changes the condition numbering for more leeway. Basic events get +100 just in case, I can imagine 10 treshold being easily crossed with related advanced logic conditions at some point, this is more than enough, but better safe than sorry to keep things organized IMO. And polling starts at much higher number for the same reason.

I tested a bunch of conditions, I'll test some more today or tommorow live, the rest will need to be checked by people as I can't really access some features too conveniently.

Once this gets merged, I'll start working on a bunch more ID/regex matching conditions (e.g. specific points rewards or prediction/poll option winning)

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Looks great!

Just found one minor issue:
The `ConditionIsSupportedByToken()` function seems to have returned `true` if either of the token options is set.
I adjusted to check if all options are set.

Also can you maybe also shorten the commit message of [c772b40](https://github.com/WarmUpTill/SceneSwitcher/pull/902/commits/c772b40c6f991d20f236e4ae78f37962f17526fd) or would you mind if I did so?

Thanks again for your contributions!

**Comment by Destroy666x** [comment]
Feel free to shorten the commit if needed

**Comment by WarmUpTill** [comment]
Just want to adhere to the general git commit guidelines to avoid the commits being cut off with the "...":
grafik

I had another look at the event handling:
I _think_ the raid events (possibly more?) might need special treatment as here the `broadcaster_user_id` filed is replaced with `to_broadcaster_user_id` and `from_broadcaster_user_id` respectively.

**Comment by Destroy666x** [comment]
Not sure what you mean, they already have special handling.

**Comment by Destroy666x** [comment]
Fixed, quick scrolling didn't show any exceptions other than raid for this field.

**Pull request merged**
