### PR TITLE
Resolve macOS network crash

### PR DESCRIPTION
**Pull request by WarmUpTill**

### CODE REVIEW

**Comment by tt2468** [comment]
Hey there, I was wondering what testing you did to determine that downgrading the deps fixed this network crash? We're having a crash issue with SceneSwitcher and obs-websocket being installed where it crashes only when both are installed, which leads us to believe there is some weird shared resource issue going on.

**Comment by WarmUpTill** [comment]
Hi, I believe that the [past](https://obsproject.com/forum/threads/obs-not-working-in-big-sur.141754/) crashes on MacOS were happening almost immediately after startup and the crashlogs were pointing to asio symbols.
So my tests were mostly limited to just rebuilding with a different version and seeing if OBS no longer crashed.

**Comment by tt2468** [comment]
This is what I'm just now discovering. We (obs-websocket) have been using the same old asio version, and logitech appears to have had this issue, used our version, and not noted it down, then I guess you saw what logitech was using and used the same version.

And we discovered this problem independently because we have been using an updated ASIO version in 5.0.0.

So this might mean we can never update asio without all releasing new versions at once, lol

**Comment by WarmUpTill** [comment]
> So this might mean we can never update asio without all releasing new versions at once, lol

That might indeed be the case.
Unless there is some way to isolate the asio dependencies.
Unfortunately I am not aware how to do that at the moment.

**Comment by tt2468** [comment]
Well they should be isolated already, because everyone statically links ASIO. I've lodged an issue with the ASIO repo to hopefully get some attention to the issue: https://github.com/chriskohlhoff/asio/issues/975

**Pull request merged**
