### PR TITLE
Improvements to Video condition

### PR DESCRIPTION
**Pull request by Oekn5w**
This change implements the following 3 improvements to the video condition:
* Show the current "best match" value in the Pattern preview window. This helps to find the desired threshold value. 
image
* Fix the loops when marking the found patterns (off-by-one errors)
* Fixes false positive matches when using the alpha channel as mask and the testing image is completely black or almost so. As the denominator in all selectable pattern matching algorithms is multiplied with the tested image, these conditions lead to a division by Zero, which sometimes gives `-inf` as result and sometimes `nan`. The latter are detected as matches in the current version. The fix is to check the values for non-finiteness before applying the threshold algorithm.

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Displaying the current matching value is a great idea!
And thank you very much for digging into the code and finding these issues! :)

**Comment by Oekn5w** [comment]
@WarmUpTill When do you think you will release the next version (that then includes this PR)?

**Comment by WarmUpTill** [comment]
Probably in a couple of weeks.
Can't give a concrete date yet unfortunately.

**Comment by Oekn5w** [comment]
Short background on why I was asking as a tool dev for a small-ish speedrun community:
Our previous method of detecting loads has become unstable since OBS 28 and we've been looking for a new video based load remover.
We (the moderators and tool-devs) are now happy with how the Load Remover is working and are ready to release it. The fix in this PR is essential for our application though.

**Pull request merged**
