### PR TITLE
Add Twitch send chat announcement and emote-only mode actions

### PR DESCRIPTION
**Pull request by Destroy666x**
image

One useful for just making messages stand out (and sending messages in the 1st place without IRC implementation), second for automatically switching to the mode when e.g. playing something for which backseating is disallowed.

One small todo that I'll do next weekend perhaps - set 500 text limit for the announcement message. Since QTextWidget doesn't support that by default, I'll try extending and event as some practice. I'd like to get this merged 1st tho to avoid conflicts: https://github.com/WarmUpTill/SceneSwitcher/pull/888

### CODE REVIEW

**Comment by WarmUpTill** [comment]
Good idea!

Sorry if I am just missing something, but is there any reason for the additional `_secondLineLayout` layout?
Or could the `_announcementMessage` widget be added to the `mainLayout` directly?

> I'd like to get this merged 1st tho to avoid conflicts

Sure, just give me a ping then when a PR is ready to merge.

Thanks again for your contributions! :)

**Comment by Destroy666x** [comment]
> Sorry if I am just missing something, but is there any reason for the additional _secondLineLayout layout?

I added it because it's quite likely that more actions in the future will require a 2nd line (one I'm consider coding in the future, for instance) and that'll prepare the code for that. Depends if you prefer "optimized for future" or "optimized for now" approach. I can add it directly for now for it to be more optimal if you'd like.

> Sure, just give me a ping then when a PR is ready to merge.

That one is, excpet it'll need the MacOS patch I presume.

**Comment by WarmUpTill** [comment]
I merged the tooltip PR.

I prefer the layout change to be revered until it is really needed.
(Reverted with https://github.com/WarmUpTill/SceneSwitcher/pull/890/commits/24b0a9e03e5899bb3c65b3652150a5b72a2e22ff)

I also prefer the emote only enabling and disabling to be separate actions instead of having to adjust the checkbox. (https://github.com/WarmUpTill/SceneSwitcher/pull/890/commits/1e8ef7b6d65a8bdb324eb7a9aa3bf24143a30baf)
Do you agree or would your rather have the checkbox approach?

**Comment by Destroy666x** [comment]
Looks ok and good to merge.

Enable/disable is better design for users indeed. The whole action might need splitting into multiple soon, though, which I was thinking about earlier without this change anyways, this only strengthented that thought a fair bit. As the dropdown could grow to huge size at one point with how many potential other actions there are, including ones that change the state in either boolean, triple or more predefined ways. And the cpp file too, although in this case that makes it a little bit more slim.

Perhaps an idea is to split into multiple thematic files:
- channel info modifications
- chat actions
- other (?)
But from the non-code perspective this is also solvable by making the dropdown searchable like the actions/conditions ones, for instance. Just a food for thought that's more a thing for another issue/PR than this one.

**Comment by WarmUpTill** [comment]
Splitting might indeed be necessary in the future, but I would suggest to tackle that once it is really necessary.

> But from the non-code perspective this is also solvable by making the dropdown searchable like the actions/conditions ones, for instance. Just a food for thought that's more a thing for another issue/PR than this one.

That should at least be rather easy to set up.

**Comment by WarmUpTill** [comment]
_Unless_ you want to split the "Twitch" action into multiple actions types (E.g. a separate "Twitch channel" and "Twitch chat" , ... action) I don't see a problem.

The migration can then be simply be made in the Save() and Load() functions.
(This is already done in various places throughout the plugin, for example [here](https://github.com/WarmUpTill/SceneSwitcher/blob/master/src/macro-core/macro-action-filter.cpp#L70-L87))

Please let me know if I should be misunderstanding something! :)

**Comment by Destroy666x** [comment]
I meant splitting, yeah.

Oh, so you create more of fallbacks than migrations, I see.

**Pull request merged**
